matrix:
  ARCH:
    - armhf
  VERSION:
    - "0.7.6"
    - "0.8.1"
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay &
    - cd $$VERSION/$$ARCH
    - docker build --tag build-image-temp --file Dockerfile.build .
    - docker run --rm --volume $PWD:/target build-image-temp
  when:
    matrix:
      ARCH: armhf

publish:
  docker:
    # image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag:
      - "$$VERSION"
      - "0.7"
    when:
      matrix:
        VERSION: "0.7.6"

  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag:
      - "$$VERSION"
      - "0.8"
      - "latest"
    when:
      matrix:
        VERSION: "0.8.1"

  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag: "$$VERSION"
    when:
      matrix:
        VERSION: "master"

# cache:
#   mount:
#     - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
