matrix:
  ARCH:
    - armhf
  VERSION:
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay &
    - cd $$VERSION/$$ARCH
    - docker build --tag build-image-temp --file Dockerfile.build .
    - docker run --rm --volume $PWD:/target build-image-temp
  when:
    matrix:
      ARCH: armhf

publish:
  docker:
    image: armhfplugins/drone-docker:docker-caching
    file: "$$VERSION/$$ARCH/Dockerfile"
    context: "$$VERSION/$$ARCH"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay

cache:
  mount:
    - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
