matrix:
  ARCH:
    - armhf
  VERSION:
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay &
    - cd $$VERSION/$$ARCH
    - docker build --file Dockerfile.build . | tee docker-build.log
    - IID=$(tail --lines 1 docker-build.log)
    - docker run --rm -v $PWD:/target $IID
  when:
    matrix:
      ARCH: armhf

publish:
  docker:
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
