build:
  image: armhfbuild/alpine:3.2
  commands:
    - sed -i 's/FROM /FROM armhfbuild\//' Dockerfile

publish:
  docker:
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    storage_driver: overlay
