# matrix:
#   VERSION:
#     - 1.5
#     - 1.4

build:
  image: armhfbuild/alpine:3.2
  commands:
    - sed -i 's/FROM /FROM armhfbuild\//' Dockerfile

publish:
  docker:
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    tag: "$$BRANCH"
    storage_driver: overlay

    # Caching
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: "$$BRANCH"
cache:
  mount:
    - docker/image.tar
