matrix:
  ARCH:
    - armhf
  VERSION:
    - "0.7.6"
    # - "0.8.1"
    #   doesn't build
    - "master"

build:
  image: armhfbuild/docker:1.10-dind
  privileged: true
  commands:
    - docker daemon --storage-driver overlay &
    - sleep 2
    - docker build --tag build-image-temp --file build/$$VERSION/Dockerfile-$$ARCH build/$$VERSION
    - docker run --rm --volume $PWD:/target build-image-temp
  when:
    matrix:
      ARCH: armhf

publish:
  hub_0_7_6:
    # image: armhfplugins/drone-docker:docker-caching
    image: armhfplugins/drone-docker
    file: publish/Dockerfile-$$ARCH
    context: publish
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag:
      - "0.7.6"
      - "0.7"
    when:
      matrix:
        ARCH: armhf
        VERSION: "0.7.6"

  hub_0_8_1:
    # image: armhfplugins/drone-docker:docker-caching
    image: armhfplugins/drone-docker
    file: publish/Dockerfile-$$ARCH
    context: publish
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag:
      - "0.8.1"
      - "0.8"
    when:
      matrix:
        ARCH: armhf
        VERSION: "0.8.1"

  hub_master:
    # image: armhfplugins/drone-docker:docker-caching
    image: armhfplugins/drone-docker
    file: publish/Dockerfile-$$ARCH
    context: publish
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/caddy
    force_tag: true
    storage_driver: overlay
    tag:
      - "master"
      - "latest"
    when:
      matrix:
        ARCH: armhf
        VERSION: "master"

# cache:
#   mount:
#     - /drone/docker

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
