FROM golang:1.5.3-alpine
RUN apk --update add git g++ gcc make linux-headers

WORKDIR src/github.com/mholt/caddy
RUN git clone --single-branch --branch v0.7.6 https://github.com/mholt/caddy . \
  && go get \
  && go build \

CMD cp ./caddy /target/caddy
